name: robotlegs_polymer
version: 0.1.1
author: Hans Van den Keybus
description: Demo of an application combining Polymer and Robotlegs for Google Dart
dependencies:
  polymer: any
  robotlegs:
    path: C:\Users\hvk\DartWorkspace\robotlegs
transformers:
- polymer:
    entry_points: web/robotlegs_polymer.html
